// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// A class that provides default [FirebaseOptions] for different platforms.
///
/// This class is generated by the FlutterFire CLI and contains the Firebase
/// project configurations for web, Android, iOS, macOS, and Windows.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Returns the [FirebaseOptions] for the current platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// The [FirebaseOptions] for the web platform.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtCMpmi__PDO75Iq_0woPJHS0oe-nj4U0',
    appId: '1:1087990046297:web:6dd8de8c03e74556f21b48',
    messagingSenderId: '1087990046297',
    projectId: 'verzusxyz-og',
    authDomain: 'verzusxyz-og.firebaseapp.com',
    storageBucket: 'verzusxyz-og.firebasestorage.app',
    measurementId: 'G-TEHP30BP40',
  );

  /// The [FirebaseOptions] for the Android platform.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC57dZH78--NIsI5dSfJRezbicwcnFch8E',
    appId: '1:1087990046297:android:a75daed1535f7766f21b48',
    messagingSenderId: '1087990046297',
    projectId: 'verzusxyz-og',
    storageBucket: 'verzusxyz-og.firebasestorage.app',
  );

  /// The [FirebaseOptions] for the iOS platform.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1tCUkgrpbz0umlOS2p3X19Ps5hVlq5SU',
    appId: '1:1087990046297:ios:71cc07b67dd1f827f21b48',
    messagingSenderId: '1087990046297',
    projectId: 'verzusxyz-og',
    storageBucket: 'verzusxyz-og.firebasestorage.app',
    iosBundleId: 'aa.verzus.xyz',
  );

  /// The [FirebaseOptions] for the macOS platform.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1tCUkgrpbz0umlOS2p3X19Ps5hVlq5SU',
    appId: '1:1087990046297:ios:71cc07b67dd1f827f21b48',
    messagingSenderId: '1087990046297',
    projectId: 'verzusxyz-og',
    storageBucket: 'verzusxyz-og.firebasestorage.app',
    iosBundleId: 'aa.verzus.xyz',
  );

  /// The [FirebaseOptions] for the Windows platform.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtCMpmi__PDO75Iq_0woPJHS0oe-nj4U0',
    appId: '1:1087990046297:web:445629a912cd693cf21b48',
    messagingSenderId: '1087990046297',
    projectId: 'verzusxyz-og',
    authDomain: 'verzusxyz-og.firebaseapp.com',
    storageBucket: 'verzusxyz-og.firebasestorage.app',
    measurementId: 'G-VC4K2D8WK5',
  );
}
